### ISSUE TITLE
Support building on linux

### ISSUE THREAD

**Issue by geeksville** [OpenSource-EBike-firmware/SW102_LCD_Bluetooth#1]
So @casainho mentioned I might be able to help getting the config stuff ported to this new controller.  I'm happy to give it a shot.  Since my controller won't be here for a few weeks I thought I'd start by getting the SDK_12.3.0 branch building with the linux toolchain (I'm starting by using tips [here](https://gustavovelascoh.wordpress.com/2017/01/23/starting-development-with-nordic-nrf5x-and-gcc-on-linux/).  Mostly to save myself from having to fire up my windows vm.

Cool?  If not, please speak up.  I'll send in a PR with necessary changes once I can build bins.

**Comment by casainho** [comment]
Don't forget to see the wiki with instructions written by Nick, for Windows. The configurations for Eclipse do apply for Linux.

I am using Ubuntu and the GCC compiler is straight forward to install as it is on Ubuntu software repositories. You just need to follow guides for ARM as NRF51 is an ARM.

**Comment by geeksville** [comment]
oh yah I just noticed - slight doc PR incoming.
