### ISSUE TITLE
Fault code 6: rxlost

### ISSUE THREAD

**Issue by geeksville** [OpenSource-EBike-firmware/SW102_LCD_Bluetooth#22]
Midway through a two hr ride I noticed it wasn't putting any power out.  I looked down and saw this fault message.  Took photo for the report and pressed power button to resume ride.  Fault did not reoccur.  

Firmware version: 0.19.9

![image](https://user-images.githubusercontent.com/225513/63037167-636b3e80-be73-11e9-80be-761b80e49c6f.png)

**Comment by geeksville** [comment]
(I think something is wonky (race condition?) in rxcomms land - I'll investigate tonight.

**Comment by lowPerformer** [comment]
I see you use a seperate tx_buffer in state.c but you can pull one from uart.c by uart_get_tx_buffer(). why not use this?

**Comment by geeksville** [comment]
tested.  confirmed fixed in 0.19.10
