### ISSUE TITLE
add a few fields to the info screen

### ISSUE THREAD

**Issue by geeksville** [OpenSource-EBike-firmware/SW102_LCD_Bluetooth#27]
@casainho no problem - so you want me to add motor RPM, ERPS and PWM duty cycle to the secondary info page?

**Comment by geeksville** [comment]
I'll get to this sometime in the next few weeks, but in the meantime these fields are visible in the config/technical menu.

**Comment by casainho** [comment]
Yes. I think will be great when they can be chosen on the main screen numeric fields or later on the bar graphic widget. On 850C they are already available on the main screen, on the graph.

**Comment by geeksville** [comment]
Moved to TODO in Color_LCD.  So closing here (moving all SW102 development/releases/issues to shared codebase).
