### ISSUE TITLE
uGUI font usage

### ISSUE THREAD

**Issue by lowPerformer** [OpenSource-EBike-firmware/SW102_LCD_Bluetooth#28]
So uGUI uses a full 255 character font set. This includes non-printable, standard and extended chars.
Especially with bigger font this uses a crazy amount of flash space.
It is an easy task to define own fonts based on the uGUI one but without the non-printable (HEX 0x00 to 0x1F) and extended (0x80 to 0xFF) chars. The really big font are normally used only for digits to save some extra space. I suggest ASCII 0x2B to 0x3B to also have some digit-associated like ',' or '.'.

So my question is: which fonts are used? Which for digit only, which one as a "full set"?

**Comment by lowPerformer** [comment]
One suggestions would be to strip off the non-printable and extended chars from the uGUI original font directly without define some new one. Just define the very reduced digits-only font. It is easier this way to switch to a new font...
I think we will never use those extended and non-printable stuff (we can define it in an extra one if we need it)...

**Comment by casainho** [comment]
On 850C, I did follow your guide the generate fonts and did only ones for numbers, so I understand what you say and I agree.

**Comment by lowPerformer** [comment]
We use 5X12 and 10X16 font from uGUI right now.
We can reduce flash space:
by 8k if we use only digits NUM_10X16
by another 2k if we strip 5X12 to only the standard ASCII chars 0x20 to 0x7E

**Comment by geeksville** [comment]
really smart.  I think this would be awesome.

Currently we use 10X16 only because of the "W" character.  Later today I'll change printing on of units to use a different font, so 10X16 can be safely change to 10X16 NUM.

**Comment by lowPerformer** [comment]
We can also extend the fonts by our "special" characters we need, f.i. ASCII ':' can be a 'W'. I did that with MY_FONT_8X12 where 0x1F is a '°' like in °C.

**Comment by geeksville** [comment]
ooh - I didn't realize you added deg symbol I'll use it.

**Comment by geeksville** [comment]
because we are moving back to Color_LCD I'm trying to close bugs here.  I think this is mostly addressed now except for "We can also extend the fonts by our "special" characters we need, f.i. ASCII ':' can be a 'W'. I did that with MY_FONT_8X12 where 0x1F is a '°' like in °C."

Which is a good idea, but to make it easy to track for now I'm just putting it in TODO.md.
