### ISSUE TITLE
use shorter strings for config entries

### ISSUE THREAD

**Issue by geeksville** [OpenSource-EBike-firmware/SW102_LCD_Bluetooth#33]
per @lowPerformer 
For me it is a bit irritating to see kph and not kmh. This is sure an European mental state.
Also the word wrap of some config entries are a bit poor. Maybe better use some abbrevations like "Wheels" instead of "Wheel settings", "pwr", "Assist lvl", ...

**Comment by lowPerformer** [comment]
Ho about this:

"Wheel settings" -> "Wheels"
"Assist level" -> "Assist lvl"
"Walk assist" -> "Walk asst"
"Startup power" -> "Boost"
"Motor temperature" -> "Motor temp"

"Max wheel speed" -> "Max speed"
"Wheel perimeter" -> "Perimeter"
"Speed units" -> "Units"
"Max current" -> "Max curr"
"Current ramp" -> "Curr ramp"
"Low cut-off" -> "Cut-off"
"Reset threshold" -> "Rst thold"
"Battery total" -> "Total Wh"
"Used" -> "Used Wh"
"Num assist levels" -> "Num assist lvl"
"Limit to max-power" -> "Limit pwr"
"Motor voltage" -> "Motor type"
"Motor assist" -> "Asst w/o pedal"

**Comment by geeksville** [comment]
Sounds great to me!

(Sent from a phone - please ignore typos)

**Comment by lowPerformer** [comment]
OK, let's close this, too.
