### ISSUE TITLE
Which gcc version to use

### ISSUE THREAD

**Issue by lowPerformer** [OpenSource-EBike-firmware/SW102_LCD_Bluetooth#36]
Right now we use different gcc versions for Windows and Linux build.
The Linux version uses "default" version 4.9.3 and I changed this for Windows to 7.3.1.

The 7.3.1 builds with -os optimization around 1k smaller code (just a fact, don't know if this is good or bad) and is overall newer and maybe fixed some bugs.
4.9.3 is the SDK12.3 default setting and therefore seems to be tested.

**Comment by casainho** [comment]
On my linux I have installed this: arm-none-eabi-gcc (15:6.3.1+svn253039-1build1) 6.3.1 20170620
It is being working for both 850C and SW102.

**Comment by geeksville** [comment]
I've been using 4.9.3 20150529.    I'm okay with anything,  but I agree we should pick one version and put it in the README (and ideally use the same version on 850C which I suspect is low risk).

**Comment by lowPerformer** [comment]
OK, then I vote for 7.3.1 because it is currently used in the repo for Windows and it is in the Howto Setup IDE for Windows. ;)
This is just for the official setup. Sure everyone can use the gcc version he/she preferres.

**Comment by geeksville** [comment]
Sounds good to me - I'll add a personal TODO to switch 7.3.1.
