### ISSUE TITLE
If bluetooth is inited, sometimes board crashes

### ISSUE THREAD

**Issue by geeksville** [OpenSource-EBike-firmware/SW102_LCD_Bluetooth#4]
I noticed this while futzing with display stuff.  Sometimes the board was spinning in app_error_fault_handler.

For the time being I've commented out ble_init() in my wip branch.  After I have main screen stuff kinda working I'm happy to investigate further and reenable bluetooth:

  // kevinh FIXME - turn off ble for now because somtimes it calls app_error_fault_handler(1...) from nrf51822_sw102_ble_advdata
  // ble_init();

**Comment by casainho** [comment]
I know that we can't debug the code while using Bluetooth as there are strict timings that the microcontroller must handle. Maybe you are halting the microcontroller or such??

**Comment by geeksville** [comment]
ooh!  Good to know, that's probably it.

**Comment by lowPerformer** [comment]
casainho is right. The fault handler is called by the SoftDevice as soon as you hit the breakpoint.
