### ISSUE TITLE
An OpenSource-EBike gitter channel?

### ISSUE THREAD

**Issue by geeksville** [OpenSource-EBike-firmware/SW102_LCD_Bluetooth#6]
Hi @casainho (and other geeks),

Would you be interested in something like a gitter (https://gitter.im/) channel for OS-EBike developers to ask questions/discuss proposals (rather than github issues)?  If so I can send in a PR that adds a gitter channel to the main repo.  We used gitter on one of the other open source projects and liked it a lot.

**Comment by casainho** [comment]
I don't know about it, I never heard. For me would be ok, I think we can try and see. I can put the link on the wiki so other developers can find it there.

**Comment by geeksville** [comment]
@casainho if you want to try it: Just go here https://gitter.im/home/explore#createcommunity and point it at your gitrepo.  They will auto generate a pull request to add a slick little chat button to your README.md.  If you or others end up not digging it (ie turns out to not be useful etc...) you can just delete that change to the README.

**Comment by geeksville** [comment]
or you can put that button in the wiki.

**Comment by casainho** [comment]
Here it is: https://gitter.im/OpenSource-EBike/community

**Comment by casainho** [comment]
And I put a link on wiki

**Comment by geeksville** [comment]
@casainho here's a better video: https://www.youtube.com/watch?v=aFR3zBxaMrc
