### ISSUE TITLE
software update over bluetooth

### ISSUE THREAD

**Issue by geeksville** [OpenSource-EBike-firmware/SW102_LCD_Bluetooth#7]
Hi @lowPerformer and @casainho, 

I think it is likely I'll have an initial alpha/betaish release out this week based on y'alls stuff.  So now I'm thinking ahead of how users will install it ;-).  I bet it is unavoidable that at least once they have to crack open a case and then carefully access those programming pads (I'm assuming the stock bootloader is locked to only load signed images).  But in the perfect world they would only have to do that for the first install.

Has anyone looked into how this MCU does software update over bluetooth (I haven't)?  i.e. is it fairly painless to start including bluetooth based sw update?  Does Nordic distribute an android/iOS app that does this (because making an android/iOS app just for sw update sounds tedious)?

**Comment by lowPerformer** [comment]
I implemented an Bluetooth bootloader which works:
https://github.com/OpenSource-EBike-firmware/SW102_LCD_Bluetooth-bootloader

There is no bootloader on the stock SW102, so users have to open the case and install the bootloader once. from then on, you can update any combination of SoftDevice/Bootloader/Firmware over the air (f.i. with nordic app on smartphone).

**Comment by casainho** [comment]
Yes, I use that Nordic bootloader at work. The example from Nordic is good.

**Comment by geeksville** [comment]
@lowperformer that sounds perfect.  I'll check out that tree and test making it part of the bin that users install once. I'll also look for the Nordic Android tool l.

**Comment by lowPerformer** [comment]
That is "nRF Toolbox".

**Comment by geeksville** [comment]
Okay worked great! (Except that the nf connect app can't see the BLE advertise from the device from my pixel 3, the same device with my pixel 2 is fine (and approx same android version).  I'll make a build rule that packages the appload with a prebuilt bootloader and appropriate crc in a single hex file for end users to install.

**Comment by geeksville** [comment]
btw - you can close this issue now.  I made a build rule in SW102 makefile called "full_install".  If you build that it bundles @lowPerformer bootloader with the softdevice and the appload and a faked out set of bootloader info (so the bootloader will use the prebuilt appload).

When distributing release .hex files it is important to distribute this one, so that when the user installs that file their device will support bluetooth OTA packages.  To build an OTA upgrade package use @lowPerformer's existing "generate_dfu_package" (after bumping up application-version).
